<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/Data_loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import pandas as pd
import numpy as np


In [4]:
# change directories to relative paths using Images1, Images2, Images3 folders

def change_dir_cols(df):  
    df_dir = df["dir"]

    dir_1 = "/content/Generated_Images_7-2-24/"
    dir_2 = "/content/Generated Images/"
    dir_3 = "/content/05-09-2024_all_images/"

    new_dir_1 = "content/Images1/"
    new_dir_2 = "content/Images2/"
    new_dir_3 = "content/Images3/"

    for i in range(len(df_dir)):
        if df_dir[i].startswith(dir_1):
            df_dir[i] = df_dir[i].replace(dir_1, new_dir_1)
        elif df_dir[i].startswith(dir_2):
            df_dir[i] = df_dir[i].replace(dir_2, new_dir_2)
        elif df_dir[i].startswith(dir_3):
            df_dir[i] = df_dir[i].replace(dir_3,new_dir_3)
        else:
            print("unrecognized directory:", df_dir[i])
    return df

In [7]:
with open("data/manual_classification_cl6.pkl", 'rb') as f:
    df = pickle.load(f) # deserialize using load()

df.head()

,class,noise,path,seed,dir
0,3,4,noise 4 20604.0.png,20604.0,/content/Generated_Images_7-2-24/
1,3,6,noise 6 20289.0.png,20289.0,/content/Generated_Images_7-2-24/
2,4,23782.0,noise 6 23782.0.png,23782.0,/content/Generated Images/
3,2,2,7761.png,7761,/content/05-09-2024_all_images/
4,1,2,8366.png,8366,/content/05-09-2024_all_images/


In [8]:
df = change_dir_cols(df)

df.head()

,class,noise,path,seed,dir
0,3,4,noise 4 20604.0.png,20604.0,content/Images1/
1,3,6,noise 6 20289.0.png,20289.0,content/Images1/
2,4,23782.0,noise 6 23782.0.png,23782.0,content/Images2/
3,2,2,7761.png,7761,content/Images3/
4,1,2,8366.png,8366,content/Images3/


In [9]:
file_name = "data/manual_classification_cl6_updated_image_dir.pkl"

with open(file_name, 'wb') as f:
        pickle.dump(df, f)

In [12]:
with open("data/2024-08-11_manual_classification.pkl", 'rb') as f:
    df1 = pickle.load(f)

df1.head()

,class,noise,path,seed,dir
0,2,2,0.png,0,/content/05-09-2024_all_images/
1,None,2,1.png,1,/content/05-09-2024_all_images/
2,2,2,2.png,2,/content/05-09-2024_all_images/
3,None,2,3.png,3,/content/05-09-2024_all_images/
4,2,2,4.png,4,/content/05-09-2024_all_images/


In [13]:
df1 = change_dir_cols(df1)

df1.head()

,class,noise,path,seed,dir
0,2,2,0.png,0,content/Images3/
1,None,2,1.png,1,content/Images3/
2,2,2,2.png,2,content/Images3/
3,None,2,3.png,3,content/Images3/
4,2,2,4.png,4,content/Images3/


In [14]:
file_name = "data/2024-08-11_manual_classification_updated_image_dir.pkl"
with open(file_name, 'wb') as f:
        pickle.dump(df1, f)

In [24]:
# add 2048 generated features to 32210 classified images frame
with open("data/Images_Classified_NN_cl6.pkl", 'rb') as f:
    class_feat_df = pickle.load(f)

with open("data/unclassified_features_NN_2048.pkl", 'rb') as f:
    feat_2048_arr = pickle.load(f)

feat_2048_df = pd.DataFrame(feat_2048_arr)
feat_2048_df.head()

feat_2048_df.columns = [f"NN_feat_{i}" for i in range(feat_2048_df.shape[1])]

class_feat_df = pd.concat([class_feat_df, feat_2048_df], axis=1)

class_feat_df.shape

with open("data/images_classified_all_features_cl6.pkl", 'wb') as f:
    pickle.dump(class_feat_df, f)
    

In [51]:
# random array from unclassified_features.pkl and manual_classification_cl6_updated_image_dir.pkl
with open("data/unclassified_features.pkl", 'rb') as f:
    unclass_df = pickle.load(f) # deserialize using load()

with open("data/manual_classification_cl6_updated_image_dir.pkl", 'rb') as f:
   man_class_df = pickle.load(f) # deserialize using load()

image_indices = unclass_df[unclass_df["path"].isin(man_class_df["path"])].index.tolist()
print(len(image_indices))

unclass_df_dropped = unclass_df.drop(image_indices)
unclass_df_dropped.shape

# generate random array of indices
#np.random.seed(42)
rand_indices = np.random.randint(low=0, high=unclass_df_dropped.shape[0], size=32210, dtype=int)

7307


In [52]:
# match random indices to random_indices_array.pkl
with open("data/random_indices_array.pkl", 'rb') as f:
    rand_indices_array = pickle.load(f) # deserialize using load()

print(rand_indices_array)
print(rand_indices)

[30606 33284 18865 ... 12878  7419 27130]
[24356 26013    94 ...   160 29135 11323]


In [60]:
# try with just 39517 images
np.random.seed(42)
rand_indices = np.random.randint(low=0, high=unclass_df_dropped.shape[0], size=39517, dtype=int)
print(rand_indices_array)
print(rand_indices)

[30606 33284 18865 ... 12878  7419 27130]
[23654 15795   860 ...  9250 30894 18873]
